#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -e

# Recreate symbolic links.
ln -sf $HOME/.dotfiles/git/.gitconfig $HOME/
if [ ! -d "$HOME/.gnupg" ]; then
    mkdir -p "$HOME/.gnupg/"
fi
ln -sf $HOME/.dotfiles/gnupg/* $HOME/.gnupg/
chmod 700 $HOME/.gnupg/
ln -sf $HOME/.dotfiles/macos/.hushlogin $HOME/
ln -sf $HOME/.dotfiles/node/.npmrc $HOME/
ln -sf $HOME/.dotfiles/vim $HOME/.vim
if [ ! -d "$HOME/Library/Application Support/Code/User/" ]; then
    mkdir -p "$HOME/Library/Application Support/Code/User/"
fi
ln -sf $HOME/.dotfiles/zsh/.zshrc $HOME/
ln -sf $HOME/.dotfiles/zsh/oh-my-zsh/materialshell-electro.zsh-theme $HOME/.oh-my-zsh/custom/themes/
