name: Dotfiles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]

    steps:
    - name: Check out the code into $HOME/.dotfiles directory
      run: |
        git clone https://github.com/$GITHUB_REPOSITORY.git $HOME/.dotfiles

    - name: Install Dotfiles
      run: |
        $HOME/.dotfiles/scripts/install.sh
